import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class EmployeeActionService {

  employData : any[] = [
    {
        "countOfRows": 7,
        "id": 7,
        "firstname": "mika",
        "midname": "ramzy",
        "lastname": "string",
        "email": "string",
        "hireType": "Contract",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 1,
        "managerid": 5,
        "departmentid": 3,
        "gender": "male",
        "education": "Bachelor's Degree",
        "schoolName": "string",
        "documentType": "passport",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "string",
        "managerLastname": "string",
        "jobtitle": "manager",
        "branchsName": "المقر الرئيسي",
        "vacationHours": 0,
        "sickLeaveHours": 0
    },
    {
        "countOfRows": 7,
        "id": 8,
        "firstname": "string",
        "midname": "string",
        "lastname": "string",
        "email": "string",
        "hireType": "Contract",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 1,
        "managerid": 5,
        "departmentid": 3,
        "gender": "string",
        "education": "Bachelor's Degree",
        "schoolName": "string",
        "documentType": "passport",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "string",
        "managerLastname": "string",
        "jobtitle": "leader",
        "branchsName": "المقر الرئيسي",
        "vacationHours": 0,
        "sickLeaveHours": 0
    },
    {
        "countOfRows": 7,
        "id": 9,
        "firstname": "string",
        "midname": "string",
        "lastname": "string",
        "email": "string",
        "hireType": "Permanent employee",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 1,
        "managerid": 5,
        "departmentid": 3,
        "gender": "string",
        "education": "Master's Degree",
        "schoolName": "string",
        "documentType": "National ID",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "string",
        "managerLastname": "string",
        "jobtitle": "المدير العام",
        "branchsName": "المقر الرئيسي",
        "vacationHours": 0,
        "sickLeaveHours": 0
    },
    {
        "countOfRows": 7,
        "id": 10,
        "firstname": "string",
        "midname": "string",
        "lastname": "string",
        "email": "string",
        "hireType": "Permanent employee",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 2,
        "managerid": 5,
        "departmentid": 3,
        "gender": "string",
        "education": "Master's Degree",
        "schoolName": "string",
        "documentType": "National ID",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "string",
        "managerLastname": "string",
        "jobtitle": "معاون المدير العام",
        "branchsName": "المقر الرئيسي",
        "vacationHours": 0,
        "sickLeaveHours": 0
    },
    {
        "countOfRows": 7,
        "id": 11,
        "firstname": "string",
        "midname": "string",
        "lastname": "string",
        "email": "string",
        "hireType": "string",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 2,
        "managerid": 5,
        "departmentid": 3,
        "gender": "string",
        "education": "string",
        "schoolName": "string",
        "documentType": "string",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "string",
        "managerLastname": "string",
        "jobtitle": "معاون المدير العام",
        "branchsName": "branchTest",
        "vacationHours": 0,
        "sickLeaveHours": 0
    },
    {
        "countOfRows": 7,
        "id": 12,
        "firstname": "ahmed",
        "midname": "string",
        "lastname": "string",
        "email": "string",
        "hireType": "string",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 2,
        "managerid": 5,
        "departmentid": 3,
        "gender": "string",
        "education": "string",
        "schoolName": "string",
        "documentType": "string",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "ahmed",
        "managerLastname": "string",
        "jobtitle": "معاون المدير العام",
        "branchsName": "branchTest",
        "vacationHours": 0,
        "sickLeaveHours": 0
    },
    {
      
        "countOfRows": 7,
        "id": 13,
        "firstname": "ahmed",
        "midname": "string",
        "lastname": "string",
        "email": "string",
        "hireType": "string",
        "phonenumber": "string",
        "hiredate": "2023-09-21T00:00:00",
        "jobid": 2,
        "managerid": 5,
        "departmentid": 3,
        "gender": "string",
        "education": "string",
        "schoolName": "string",
        "documentType": "string",
        "docNo": "string",
        "streetAddress": "string",
        "postalCode": "string",
        "city": "string",
        "state": "string",
        "country": "string",
        "name": "إدارة الحساب الالى",
        "managerFirstname": "ahmed",
        "managerLastname": "string",
        "jobtitle": "معاون المدير العام",
        "branchsName": "branchTest",
        "vacationHours": 0,
        "sickLeaveHours": 0
    }
]

  baseUrl = 'https://localhost:7281'

  constructor(private _HttpClient : HttpClient) { }

  addNewEmployee(modal : {}):Observable<{}>{
  return this._HttpClient.post(`${this.baseUrl}/api/HR/Employees/Post`,modal)  
  }
  GetAllEmployees(PageNo: number,PageSize: number):Observable<any>{    
    return this._HttpClient.get(`${this.baseUrl}/api/HR/Employees/GetAll?PageNo=${PageNo}&PageSize=${PageSize}&SearchColumn=Lastname&SortColumn=Lastname&SortOrder=ASC`)
  }
  DeleteEmployee(id : number):Observable<any>{
    return this._HttpClient.delete(`${this.baseUrl}/api/HR/Employees/Delete/${id}`)
  }
  UpdateEmployee(id : number,modal : {}):Observable<any>{
    return this._HttpClient.put(`${this.baseUrl}/api/HR/Employees/Put/${id}`, modal)
  }

}
